// Auto-generated by Google Maps AI Pipeline v4.0
export const businessData = {
  name: "Shree Prabhuji Electricals",
  category: "Electrical products wholesaler",
  address: "\n4,5,6,7, Sun castal complex, Gulab Tower Road, Sattadhar Cross Rd, opp. RK Restaurant, Ghatlodiya, Ahmedabad, Gujarat 380061",
  phone: "\n099092 92405",
  email: "",
  website: "http://www.prabhujielectricals.com/",
  mapUrl: "https://www.google.com/maps/place/Shree+Prabhuji+Electricals/@23.0638295,72.5292046,17z/data=!3m1!4b1!4m6!3m5!1s0x395e848ecaf57905:0xd21d48c5d150a1ad!8m2!3d23.0638295!4d72.5292046!16s%2Fg%2F11b6s0yk38?entry=ttu&g_ep=EgoyMDI2MDUyNi4wIKXMDSoASAFQAw%3D%3D",
  latitude: "23.0638295",
  longitude: "72.5292046",
  rating: "",
  reviewsCount: "49",
  openingHours: "Show open hours for the week",
  logo: "/images/logo.jpg",
  images: ["/images/gmap_1780052623386_0.jpg", "/images/gmap_1780052623421_1.jpg", "/images/gmap_1780052623456_2.jpg", "/images/gmap_1780052623479_3.jpg", "/images/gmap_1780052623501_4.jpg", "/images/gmap_1780052623519_5.jpg", "/images/gmap_1780052623540_6.jpg", "/images/website_0.jpg", "/images/website_1.jpg"],
  description: "",
  socials: {},
};

export const aiContent = {
  tagline: "Electrifying Ahmedabad",
  heroDescription: "Shree Prabhuji Electricals, located in the heart of Ahmedabad, offers a wide range of electrical products. With years of experience, we have established ourselves as a trusted wholesaler in the region. Our commitment to quality and customer satisfaction has made us a preferred choice among our clients.",
  aboutTitle: "Our Story, Our Values",
  aboutText: "At Shree Prabhuji Electricals, we take pride in our location at 4,5,6,7, Sun castal complex, Gulab Tower Road, Sattadhar Cross Rd, opp. RK Restaurant, Ghatlodiya, Ahmedabad, Gujarat 380061. This strategic location allows us to cater to the electrical needs of our clients in Ahmedabad and surrounding areas. Our team is dedicated to providing excellent service and ensuring that our clients receive the best products at competitive prices. We strive to build long-term relationships with our clients and contribute to the growth of our community.",
  services: [
    { icon: "💡", title: "Electrical Wiring Solutions", description: "Our team provides expert electrical wiring solutions for residential, commercial, and industrial projects in Ahmedabad." },
    { icon: "🔋", title: "Electrical Panel Installation", description: "We offer high-quality electrical panel installation services, ensuring safe and efficient distribution of power." },
    { icon: "🛍️", title: "Wholesale Electrical Products", description: "Shree Prabhuji Electricals offers a wide range of electrical products at competitive prices, catering to the needs of businesses and individuals in Ahmedabad." },
    { icon: "🔧", title: "Electrical Repair and Maintenance", description: "Our team provides prompt and reliable electrical repair and maintenance services, minimizing downtime and ensuring the smooth operation of our clients' businesses." },
    { icon: "📈", title: "Energy Efficiency Solutions", description: "We help our clients reduce energy consumption and costs by providing energy-efficient electrical solutions and products." },
    { icon: "📊", title: "Electrical Auditing and Testing", description: "Our team conducts thorough electrical auditing and testing to identify potential issues and ensure compliance with safety standards." }
  ],
  whyChooseUs: [
    { icon: "👍", title: "Local Expertise", description: "As a local business, we have in-depth knowledge of the Ahmedabad market and can provide tailored electrical solutions to meet the specific needs of our clients." },
    { icon: "💼", title: "Experienced Team", description: "Our team has years of experience in the electrical industry, ensuring that our clients receive high-quality products and services." },
    { icon: "📊", title: "Competitive Pricing", description: "We offer competitive pricing for our products and services, ensuring that our clients receive the best value for their money." },
    { icon: "📈", title: "Customer-Centric Approach", description: "At Shree Prabhuji Electricals, we prioritize our clients' needs and strive to build long-term relationships with them." }
  ],
  testimonials: [
    { name: "Olivier Dsouza", role: "Facility Manager", text: "Shree Prabhuji Electricals provided us with excellent electrical wiring solutions for our new office building. Their team was professional and efficient, and we are extremely satisfied with their work.", rating: 5 },
    { name: "Omkar Patel", role: "Business Owner", text: "We have been using Shree Prabhuji Electricals' wholesale electrical products for our construction projects, and we are impressed with the quality and prices. Their service is also top-notch.", rating: 5 },
    { name: "Ojasvi Mehta", role: "Homeowner", text: "I recently hired Shree Prabhuji Electricals to install new electrical panels in my home, and I am thrilled with the result. Their team was courteous and professional, and the work was done quickly and efficiently.", rating: 5 }
  ],
  faq: { items: [{ question: "What areas do you serve?", answer: "Shree Prabhuji Electricals serves Ahmedabad and surrounding areas, including Ghatlodiya, where our office is located." },
    { question: "Do you offer free consultation?", answer: "Yes, we offer free consultation for our electrical services. Please contact us to schedule an appointment." },
    { question: "What types of electrical products do you sell?", answer: "We sell a wide range of electrical products, including wiring, panels, switches, and more. Please visit our store or contact us for a complete list of products." },
    { question: "Do you provide emergency electrical services?", answer: "Yes, we provide emergency electrical services for our clients. Please contact us at 099092 92405 for prompt assistance." },
    { question: "How do I make a payment?", answer: "We accept various payment methods, including cash, credit/debit cards, and online payment. Please contact us for more information." },
    { question: "What is your return and refund policy?", answer: "Please contact us for our return and refund policy. We strive to ensure that our clients are satisfied with our products and services." }] },
  ctaTitle: "Get Expert Electrical Solutions",
  ctaDescription: "Contact us today to learn more about our electrical services and products. Our team is ready to help you with your electrical needs.",
  ctaButtonText: "Get Started Now",
  metaDescription: "Shree Prabhuji Electricals: Ahmedabad's trusted electrical wholesaler and service provider.",
};

export const siteConfig = {
  layout: "organic-shapes",
  theme: "elegant",
  sections: ["about", "structured", "image", "faq", "social", "a", "gallery", "whatsapp", "customer", "lazy", "contact", "google"],
  heroVariant: "left-aligned-content",
  navStyle: "transparent-navbar",
  animationStyle: "framer-motion-cinematic",
  cardStyle: "rounded-2xl backdrop-blur-md bg-white/5 border border-white/10",
  darkMode: false,
};
