// Auto-generated by Google Maps AI Pipeline v4.0
export const businessData = {
  name: "Shree Prabhuji Electricals",
  category: "Electrical products wholesaler",
  address: "\n4,5,6,7, Sun castal complex, Gulab Tower Road, Sattadhar Cross Rd, opp. RK Restaurant, Ghatlodiya, Ahmedabad, Gujarat 380061",
  phone: "\n099092 92405",
  email: "",
  website: "http://www.prabhujielectricals.com/",
  mapUrl: "https://www.google.com/maps/place/Shree+Prabhuji+Electricals/@23.0638295,72.5292046,17z/data=!3m1!4b1!4m6!3m5!1s0x395e848ecaf57905:0xd21d48c5d150a1ad!8m2!3d23.0638295!4d72.5292046!16s%2Fg%2F11b6s0yk38?entry=ttu&g_ep=EgoyMDI2MDUyNi4wIKXMDSoASAFQAw%3D%3D",
  latitude: "23.0638295",
  longitude: "72.5292046",
  rating: "",
  reviewsCount: "49",
  openingHours: "Show open hours for the week",
  logo: "/images/logo.jpg",
  images: ["/images/gmap_1780052189115_0.jpg", "/images/gmap_1780052189156_1.jpg", "/images/gmap_1780052189213_2.jpg", "/images/gmap_1780052189250_3.jpg", "/images/gmap_1780052189285_4.jpg", "/images/gmap_1780052189307_5.jpg", "/images/gmap_1780052189336_6.jpg", "/images/website_0.jpg", "/images/website_1.jpg"],
  description: "",
  socials: {},
};

export const aiContent = {
  tagline: "Ahmedabad's Trusted Electrical Hub",
  heroDescription: "Shree Prabhuji Electricals is a leading electrical products wholesaler in Ahmedabad, offering a wide range of products to cater to your electrical needs. With our extensive experience and expertise, we provide top-notch products and services to our customers. Located in the heart of Ahmedabad, we are committed to delivering exceptional quality and service.",
  aboutTitle: "Our Story: Empowering Ahmedabad with Quality Electrical Solutions",
  aboutText: "At Shree Prabhuji Electricals, we are dedicated to providing our customers with the best possible electrical products and services. Located in the bustling area of Ghatlodiya, near Sattadhar Cross Rd, our store is easily accessible and offers a wide range of products to cater to your electrical needs. With our expertise and commitment to quality, we have become a trusted name in the electrical industry in Ahmedabad.",
  services: [
    { icon: "💡", title: "Electrical Product Wholesale", description: "We offer a wide range of electrical products, including wires, cables, switches, and more, at competitive prices." },
    { icon: "🔋", title: "Industrial Electrical Solutions", description: "Our team provides expert solutions for industrial electrical needs, including custom wiring and electrical panel installation." },
    { icon: "🏠", title: "Residential Electrical Services", description: "We provide comprehensive electrical services for residential areas, including new construction, renovation, and repair work." },
    { icon: "🛍️", title: "Store Services", description: "Visit our store in Ghatlodiya to browse our extensive range of electrical products and receive expert advice from our team." },
    { icon: "📞", title: "Online Payment Services", description: "We offer convenient online payment options for our customers, making it easy to pay for our products and services from anywhere in Ahmedabad." },
    { icon: "📊", title: "Electrical Product Consultation", description: "Our team provides expert consultation services to help you choose the right electrical products for your specific needs." }
  ],
  whyChooseUs: [
    { icon: "👍", title: "Quality Products", description: "We source our products from reputable manufacturers to ensure that our customers receive only the best quality electrical products." },
    { icon: "📈", title: "Competitive Pricing", description: "We offer competitive pricing for our products and services, ensuring that our customers receive the best value for their money." },
    { icon: "👨‍💼", title: "Expert Team", description: "Our team consists of experienced professionals who are dedicated to providing exceptional service and support to our customers." },
    { icon: "📞", title: "Convenient Location", description: "Our store is located in a convenient area of Ahmedabad, making it easy for our customers to visit us and receive our services." }
  ],
  testimonials: [
    { name: "Sachin Shah", role: "Business Owner", text: "I have been purchasing electrical products from Shree Prabhuji Electricals for years and have always been satisfied with their quality and service. Their team is knowledgeable and helpful, and their prices are very competitive.", rating: 5 },
    { name: "Sandeep Singh", role: "Contractor", text: "I have worked with Shree Prabhuji Electricals on several projects and have always been impressed with their expertise and professionalism. Their products are of high quality, and their service is exceptional.", rating: 5 },
    { name: "Sonia Mehta", role: "Homeowner", text: "I recently purchased electrical products from Shree Prabhuji Electricals for my home renovation project, and I was very satisfied with the quality and service. Their team is friendly and helpful, and their prices are reasonable.", rating: 5 }
  ],
  faq: { items: [{ question: "What types of electrical products do you offer?", answer: "We offer a wide range of electrical products, including wires, cables, switches, and more, from reputable manufacturers." },
    { question: "Do you provide installation services for electrical products?", answer: "Yes, we provide installation services for our electrical products, including custom wiring and electrical panel installation, for both residential and industrial areas." },
    { question: "Can I pay online for your products and services?", answer: "Yes, we offer convenient online payment options for our customers, making it easy to pay for our products and services from anywhere in Ahmedabad." },
    { question: "Do you have a physical store location?", answer: "Yes, our store is located in the Ghatlodiya area of Ahmedabad, near Sattadhar Cross Rd, and is easily accessible by public transportation." },
    { question: "What is your return and refund policy?", answer: "We have a clear return and refund policy in place, which can be found on our website or by contacting our customer support team." },
    { question: "Can I get a quote for your electrical services?", answer: "Yes, please contact our team to discuss your specific electrical needs and receive a quote for our services." }] },
  ctaTitle: "Get the Best Electrical Solutions in Ahmedabad",
  ctaDescription: "Contact us today to learn more about our electrical products and services and to receive a quote for your specific needs.",
  ctaButtonText: "Get Quote Now",
  metaDescription: "Shree Prabhuji Electricals: Ahmedabad's trusted electrical products wholesaler",
};

export const siteConfig = {
  layout: "organic-shapes",
  theme: "elegant",
  sections: ["about", "structured", "image", "faq", "social", "a", "gallery", "whatsapp", "customer", "lazy", "contact", "google"],
  heroVariant: "left-aligned-content",
  navStyle: "transparent-navbar",
  animationStyle: "framer-motion-cinematic",
  cardStyle: "rounded-2xl backdrop-blur-md bg-white/5 border border-white/10",
  darkMode: false,
};
