// Auto-generated by Google Maps AI Pipeline v4.0
export const businessData = {
  name: "Shree Prabhuji Electricals",
  category: "Electrical products wholesaler",
  address: "\n4,5,6,7, Sun castal complex, Gulab Tower Road, Sattadhar Cross Rd, opp. RK Restaurant, Ghatlodiya, Ahmedabad, Gujarat 380061",
  phone: "\n099092 92405",
  email: "",
  website: "http://www.prabhujielectricals.com/",
  mapUrl: "https://www.google.com/maps/place/Shree+Prabhuji+Electricals/@23.0638295,72.5292046,790m/data=!3m2!1e3!4b1!4m6!3m5!1s0x395e848ecaf57905:0xd21d48c5d150a1ad!8m2!3d23.0638295!4d72.5292046!16s%2Fg%2F11b6s0yk38?entry=ttu&g_ep=EgoyMDI2MDUyNi4wIKXMDSoASAFQAw%3D%3D",
  latitude: "23.0638295",
  longitude: "72.5292046",
  rating: "",
  reviewsCount: "49",
  openingHours: "Show open hours for the week",
  logo: "/images/logo.jpg",
  images: ["/images/gmap_1780050925097_0.jpg", "/images/gmap_1780050925131_1.jpg", "/images/gmap_1780050925175_2.jpg", "/images/gmap_1780050925206_3.jpg", "/images/gmap_1780050925246_4.jpg", "/images/gmap_1780050925269_5.jpg", "/images/gmap_1780050925296_6.jpg", "/images/website_0.jpg", "/images/website_1.jpg"],
  description: "",
  socials: {},
};

export const aiContent = {
  tagline: "Gujarat's Trusted Electrical Partner",
  heroDescription: "Shree Prabhuji Electricals is a leading wholesaler of electrical products in Ahmedabad, Gujarat. Our extensive range of products caters to the diverse needs of our customers. With a strong presence in the industry, we have established ourselves as a reliable partner for all electrical requirements.",
  aboutTitle: "Empowering Ahmedabad's Electrical Landscape",
  aboutText: "Located in the heart of Ahmedabad, at  4,5,6,7, Sun castal complex, Gulab Tower Road, Sattadhar Cross Rd, opp. RK Restaurant, Ghatlodiya, our team at Shree Prabhuji Electricals is dedicated to providing top-notch electrical products and exceptional customer service. Our strategic location enables us to efficiently serve our customers across Gujarat. With a commitment to quality and customer satisfaction, we have built a loyal customer base in the region.",
  services: [
    { icon: "💡", title: "Electrical Products Wholesale", description: "We offer a wide range of electrical products, including wires, cables, switches, and more, catering to the diverse needs of our customers in Ahmedabad and beyond." },
    { icon: "🔌", title: "Industrial Electrical Solutions", description: "Our team provides specialized electrical solutions for industrial clients, ensuring efficient and safe electrical systems for their operations." },
    { icon: "🏠", title: "Residential Electrical Supply", description: "We supply high-quality electrical products for residential projects, including apartments, houses, and villas, in Ahmedabad and surrounding areas." },
    { icon: "🚧", title: "Construction Electrical Materials", description: "Shree Prabhuji Electricals provides a comprehensive range of electrical materials for construction projects, including building wires, cables, and other essential products." },
    { icon: "🔧", title: "Electrical Accessories", description: "Our store offers a variety of electrical accessories, such as switches, sockets, and circuit breakers, to complement our range of electrical products." },
    { icon: "📦", title: "Online Payment and Delivery", description: "For the convenience of our customers, we offer online payment options and timely delivery of our products across Ahmedabad and Gujarat." }
  ],
  whyChooseUs: [
    { icon: "💯", title: "Quality Products", description: "At Shree Prabhuji Electricals, we ensure that all our products meet the highest standards of quality, reliability, and safety." },
    { icon: "📈", title: "Competitive Pricing", description: "We offer competitive pricing for our electrical products, ensuring that our customers get the best value for their money." },
    { icon: "👥", title: "Experienced Team", description: "Our team of experts has extensive experience in the electrical industry, providing valuable advice and support to our customers." },
    { icon: "📞", title: "Prompt Customer Service", description: "We pride ourselves on our prompt and efficient customer service, responding to customer queries and concerns in a timely manner." }
  ],
  testimonials: [
    { name: "Deepa Iyer", role: "Google Review", text: "Worst experience. We had called to repair our gas stove but after checking he said not repairable and asked to exchange with a new gas stove of Laxmi brand. But after using for only 2 months the middle burner started making sound and when … More", rating: 1 },
    { name: "Deepa Padmakumar", role: "Google Review", text: "Worst experience as no after sales services. As if u call them, they only say we will come and after 5 to 6 calls they just stop picking ur call. Pls don't buy from such shops 🙏 …", rating: 1 },
    { name: "R.B. Pipalia", role: "Google Review", text: "Good number of options of fans.\nWell explained product details.\nLowest price.", rating: 5 },
    { name: "alok.srivastava jnch", role: "Google Review", text: "Worst after-sales experience. After buying fans and tubelights worth Rs. 23000/-, they want u to visit their store multiple times for their mistake. One of d designer fans had different colour blades. For exchange, no support. U r left high and dry and with bad after-taste. My suggestion: AVOID THIS OUTLET.", rating: 1 },
    { name: "Ashvin Sankhat", role: "Google Review", text: "Eloctronic all items availabal, cropten siling fen, tabale fen, Gijer, lamp, iron, etc", rating: 5 }
  ],
  faq: { items: [{ question: "What types of electrical products do you offer?", answer: "We offer a wide range of electrical products, including wires, cables, switches, and more, catering to the diverse needs of our customers in Ahmedabad and beyond." },
    { question: "Do you provide online payment options?", answer: "Yes, we offer online payment options for the convenience of our customers. You can pay for our products using various online payment methods." },
    { question: "What is your delivery policy?", answer: "We offer timely delivery of our products across Ahmedabad and Gujarat. Our delivery team ensures that our products reach our customers in a safe and efficient manner." },
    { question: "Can I return or exchange a product?", answer: "Yes, we have a returns and exchanges policy in place. Please contact our customer service team for more information on our returns and exchanges procedure." },
    { question: "How do I contact Shree Prabhuji Electricals?", answer: "You can contact us by phone at 099092 92405 or visit our website at http://www.prabhujielectricals.com/ for more information about our products and services." },
    { question: "What is your business address?", answer: "Our business address is  4,5,6,7, Sun castal complex, Gulab Tower Road, Sattadhar Cross Rd, opp. RK Restaurant, Ghatlodiya, Ahmedabad, Gujarat 380061." }] },
  ctaTitle: "Get the Best Electrical Products and Services",
  ctaDescription: "Contact us today to learn more about our electrical products and services. Our team is dedicated to providing you with the best solutions for your electrical needs.",
  ctaButtonText: "Explore Our Products",
  metaDescription: "Shree Prabhuji Electricals - Ahmedabad's trusted electrical products wholesaler",
};

export const siteConfig = {
  layout: "organic-shapes",
  theme: "elegant",
  sections: ["about", "a", "customer", "google", "image", "gallery", "testimonials", "social", "structured", "faq", "contact", "whatsapp", "lazy"],
  heroVariant: "left-aligned-content",
  navStyle: "transparent-navbar",
  animationStyle: "framer-motion-cinematic",
  cardStyle: "rounded-2xl backdrop-blur-md bg-white/5 border border-white/10",
  darkMode: false,
};
